Repository zenbitETH/zengo, pull requests merged in 2023-09, with the labels that each got.

#60 Add Global States Contract
  apps/contracts/contracts/Constants.sol
  apps/contracts/contracts/States.sol
  apps/contracts/contracts/Zengo.sol
  apps/contracts/contracts/interfaces/IStates.sol
Labels: solidity

#62 Add moderatorStruct
  apps/contracts/contracts/Zengo.sol
  apps/contracts/contracts/lib/Structs.sol
  apps/contracts/contracts/storage/ZengoStorage.sol
Labels: enhancement

#70 Restructure to add getter functions
  apps/contracts/contracts/Zengo.sol
  apps/contracts/contracts/lib/Structs.sol
  apps/contracts/contracts/storage/ZengoStorage.sol
Labels: enhancement, solidity

#69 Feat/contract functions
  apps/application/.env.example
  apps/application/abi/SpaceTimeDAO.abi.json
  apps/application/components/Carousel.tsx
  apps/application/components/Form1.tsx
  apps/application/components/Form2.tsx
  apps/application/components/Form3.tsx
  apps/application/components/Form4.tsx
  apps/application/components/Header.tsx
  apps/application/components/Layout.tsx
  apps/application/components/Map.tsx
  apps/application/components/Onboarding/InstallWallet.tsx
  apps/application/components/Onboarding/OnboardingCitizens.tsx
  apps/application/components/Onboarding/OnboardingMods.tsx
  apps/application/components/OnboardingStepper.tsx
  apps/application/components/WalletButton.tsx
  apps/application/const/contracts.ts
  apps/application/contexts/GlobalStageCycleContext.tsx
  apps/application/contexts/OnboardingContext.tsx
  apps/application/contexts/ProposalsContext.tsx
  apps/application/interfaces/index.ts
  apps/application/next.config.js
  apps/application/pages/_app.tsx
  apps/application/pages/api/poaps/claim.ts
  apps/application/pages/api/poaps/geteventinfo.ts
  apps/application/pages/api/poaps/scan.ts
  apps/application/pages/index.tsx
  apps/application/pages/modsceremony.tsx
  apps/application/pages/newProposal.tsx
  apps/application/pages/onboarding/mods/index.tsx
  apps/application/pages/onboarding/mods/poap.tsx
  apps/application/pages/onboarding/mods/register.tsx
  apps/application/pages/proposals/new.tsx
  apps/application/styles/globals.css
  apps/application/thirdweb.json
  apps/application/tsconfig.json
  apps/contracts/contracts/storage/ZengoStorage.sol
  apps/contracts/package.json
Labels: enhancement, frontend

#74 Feat/governance cycle
  apps/contracts/contracts/Constants.sol
  apps/contracts/contracts/States.sol
  apps/contracts/contracts/Zengo.sol
  apps/contracts/contracts/lib/Structs.sol
  apps/contracts/contracts/storage/ZengoStorage.sol
Labels: bug
